[Assembly: System.Reflection.AssemblyTitle("NBoard")]
[Assembly: System.Reflection.AssemblyDescription("Professional Digital Whiteboard for Windows")]
[Assembly: System.Reflection.AssemblyConfiguration("")]
[Assembly: System.Reflection.AssemblyCompany("Naajmul Hassan")]
[Assembly: System.Reflection.AssemblyProduct("NBoard")]
[Assembly: System.Reflection.AssemblyCopyright("Copyright © 2024")]
[Assembly: System.Reflection.AssemblyTrademark("")]
[Assembly: System.Reflection.AssemblyCulture("")]
[Assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[Assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[Assembly: System.Runtime.InteropServices.ComVisible(false)]
[Assembly: System.Runtime.InteropServices.Guid("12345678-1234-1234-1234-123456789012")]